VIA_ENABLE = yes
VIAL_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
REPEAT_KEY_ENABLE = yes
UNICODEMAP_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
RAW_ENABLE = yes
